Repository jdalfons/search_engine, pull requests merged in 2024-01, with the labels that each got.

#6 Process td3 td5
  README.md
  config.py
  data/subjects.csv
  main.ipynb
  main.py
  modules/Author copy.py
  modules/Corpus copy.py
  modules/Corpus.py
  modules/Document copy.py
  modules/Document.py
  modules/arxiv_api copy.py
  modules/arxiv_api.py
  modules/factory.py
  modules/reddit_api copy.py
  modules/reddit_api.py
  program.py
  requirements.txt
  tests.py
  tests/test_arxiv_api.py
  tests/test_document.py
  tests/test_reddit_api.py
  utils/tools.py
Labels: bug, documentation, enhancement

#12 Enhacement TD3-TD10:
  main.py
  modules/corpus.py
  modules/document.py
  utils/program.py
  utils/tools.py
Labels: enhancement

#11 Process td3 td10
  .gitignore
  README.md
  config.py
  data/corpus_Economics.pkl
  data/corpus_MachineLearning.pkl
  data/corpus_astronomy.pkl
  data/corpus_biology.pkl
  data/corpus_compsci.pkl
  data/corpus_geology.pkl
  data/corpus_math.pkl
  data/corpus_statistics.pkl
  data/data_reddit_arxiv_MachineLearning.csv
  data/subjects.csv
  main.ipynb
  main.py
  modules/api.py
  modules/arxiv_api.py
  modules/auth.py
  modules/author.py
  modules/corpus.py
  modules/document.py
  modules/factory.py
  modules/reddit_api.py
  modules/singleton.py
  program.py
  requirements.txt
  tests/test_arxiv_api.py
  tests/test_corpus.py
  tests/test_document.py
  tests/test_reddit_api.py
  utils/func_processing.py
  utils/func_retrieval.py
  utils/tools.py
Labels: documentation, enhancement
